/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Maykin Perdomo
 */
public class frmBuque extends javax.swing.JInternalFrame {

    /**
     * Creates new form Buque
     */
    public frmBuque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Btnsalir = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        BtnAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtidbuque = new javax.swing.JTextField();
        txtnombrebuque = new javax.swing.JTextField();
        txttipobuque = new javax.swing.JTextField();
        txtnivelesb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txttamañob = new javax.swing.JTextField();
        txtnumcamarot = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Candara", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Buscar Buque");

        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(38, 116, 162));

        jTextField1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lup32.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Candara", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Buscar Buque");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(298, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 870, 66);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        Btnsalir.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        Btnsalir.setForeground(new java.awt.Color(17, 51, 71));
        Btnsalir.setText("Salir");
        Btnsalir.setBorder(null);
        Btnsalir.setBorderPainted(false);
        jPanel1.add(Btnsalir);
        Btnsalir.setBounds(610, 420, 150, 30);

        BtnEliminar.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        BtnEliminar.setForeground(new java.awt.Color(17, 51, 71));
        BtnEliminar.setText("Eliminar");
        BtnEliminar.setBorder(null);
        BtnEliminar.setBorderPainted(false);
        jPanel1.add(BtnEliminar);
        BtnEliminar.setBounds(460, 420, 140, 30);

        BtnActualizar.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        BtnActualizar.setForeground(new java.awt.Color(17, 51, 71));
        BtnActualizar.setText("Actualizar");
        BtnActualizar.setBorder(null);
        BtnActualizar.setBorderPainted(false);
        jPanel1.add(BtnActualizar);
        BtnActualizar.setBounds(310, 420, 140, 30);

        BtnAgregar.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(17, 51, 71));
        BtnAgregar.setText("Agregar");
        BtnAgregar.setBorder(null);
        BtnAgregar.setBorderPainted(false);
        jPanel1.add(BtnAgregar);
        BtnAgregar.setBounds(160, 420, 140, 30);

        jTable1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 870, 110);

        txtidbuque.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtidbuque.setForeground(new java.awt.Color(255, 255, 255));
        txtidbuque.setBorder(null);
        jPanel1.add(txtidbuque);
        txtidbuque.setBounds(240, 240, 160, 19);

        txtnombrebuque.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtnombrebuque.setForeground(new java.awt.Color(255, 255, 255));
        txtnombrebuque.setBorder(null);
        txtnombrebuque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrebuqueActionPerformed(evt);
            }
        });
        jPanel1.add(txtnombrebuque);
        txtnombrebuque.setBounds(240, 360, 160, 19);

        txttipobuque.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txttipobuque.setForeground(new java.awt.Color(255, 255, 255));
        txttipobuque.setBorder(null);
        jPanel1.add(txttipobuque);
        txttipobuque.setBounds(540, 300, 160, 19);

        txtnivelesb.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtnivelesb.setForeground(new java.awt.Color(255, 255, 255));
        txtnivelesb.setBorder(null);
        jPanel1.add(txtnivelesb);
        txtnivelesb.setBounds(540, 360, 160, 19);

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Buque");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(190, 220, 64, 19);

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Nombre ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(190, 340, 59, 19);

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tamaño");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(190, 280, 54, 19);

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Niveles");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(430, 340, 53, 20);

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Numero Camarote");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(430, 220, 126, 19);

        jLabel13.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ID Tipo de Buque");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(430, 280, 120, 19);

        jComboBox3.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(600, 510, 210, 25);

        jLabel14.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Buque");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(540, 510, 46, 19);

        txttamañob.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txttamañob.setForeground(new java.awt.Color(255, 255, 255));
        txttamañob.setBorder(null);
        jPanel1.add(txttamañob);
        txttamañob.setBounds(240, 300, 160, 19);

        txtnumcamarot.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtnumcamarot.setForeground(new java.awt.Color(255, 255, 255));
        txtnumcamarot.setBorder(null);
        jPanel1.add(txtnumcamarot);
        txtnumcamarot.setBounds(540, 240, 160, 19);

        jLabel15.setFont(new java.awt.Font("Gill Sans MT", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Buques");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(380, 130, 129, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icono100x100_1.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 470, 100, 110);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/buques.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 110, 870, 710);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 60, 870, 566);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombrebuqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrebuqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrebuqueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton Btnsalir;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtidbuque;
    private javax.swing.JTextField txtnivelesb;
    private javax.swing.JTextField txtnombrebuque;
    private javax.swing.JTextField txtnumcamarot;
    private javax.swing.JTextField txttamañob;
    private javax.swing.JTextField txttipobuque;
    // End of variables declaration//GEN-END:variables
}
