/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.ConexionBasedeDatos;
import Clases.ProcedimientoBuquesandCamarotes;
import static GUI.frmBuque.res;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andres Martinez
 */
public class frmCamarote extends javax.swing.JInternalFrame {

    ///variables para hacer busqueda///
    Connection cn = ConexionBasedeDatos.getConexion();
    DefaultTableModel modelo = new DefaultTableModel();
    PreparedStatement ps = null;
    Statement stModel = null;
    ResultSet rsModelo = null;
    //////////////////////////

    public frmCamarote() {
        initComponents();
        cargatablebCamarotes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Btnagregar = new javax.swing.JButton();
        Btnupdate = new javax.swing.JButton();
        Btndelet = new javax.swing.JButton();
        Btnlimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtidbuque = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtidcamarote = new javax.swing.JTextField();
        txtxantdadCamar = new javax.swing.JTextField();
        txtDescCam = new javax.swing.JTextField();
        txtprecio1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtbusqueda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnbuscar1 = new javax.swing.JButton();
        txtprecio2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtprecio3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(26, 78, 108));
        jPanel1.setLayout(null);

        jTable1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Camarote", "Cantidad Camas", "Descipcion Camarote", "Precio", "Id Buque"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 70, 950, 120);

        Btnagregar.setBackground(new java.awt.Color(204, 204, 204));
        Btnagregar.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        Btnagregar.setForeground(new java.awt.Color(51, 51, 51));
        Btnagregar.setText("Agregar");
        Btnagregar.setBorder(null);
        Btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnagregarActionPerformed(evt);
            }
        });
        jPanel1.add(Btnagregar);
        Btnagregar.setBounds(250, 480, 100, 30);

        Btnupdate.setBackground(new java.awt.Color(204, 204, 204));
        Btnupdate.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        Btnupdate.setForeground(new java.awt.Color(51, 51, 51));
        Btnupdate.setText("Actualizar");
        Btnupdate.setBorder(null);
        Btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(Btnupdate);
        Btnupdate.setBounds(370, 480, 100, 30);

        Btndelet.setBackground(new java.awt.Color(204, 204, 204));
        Btndelet.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        Btndelet.setForeground(new java.awt.Color(51, 51, 51));
        Btndelet.setText("Eliminar");
        Btndelet.setBorder(null);
        Btndelet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtndeletActionPerformed(evt);
            }
        });
        jPanel1.add(Btndelet);
        Btndelet.setBounds(490, 480, 100, 30);

        Btnlimpiar.setBackground(new java.awt.Color(204, 204, 204));
        Btnlimpiar.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        Btnlimpiar.setForeground(new java.awt.Color(51, 51, 51));
        Btnlimpiar.setText("Limpiar");
        Btnlimpiar.setBorder(null);
        Btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnlimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(Btnlimpiar);
        Btnlimpiar.setBounds(600, 480, 100, 30);

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cantidad Camas");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 340, 112, 19);

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripcion camarote");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(510, 260, 153, 19);

        txtidbuque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidbuqueActionPerformed(evt);
            }
        });
        txtidbuque.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidbuqueKeyTyped(evt);
            }
        });
        jPanel1.add(txtidbuque);
        txtidbuque.setBounds(600, 390, 140, 30);

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID camarote");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(170, 270, 83, 19);

        txtidcamarote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidcamaroteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidcamaroteKeyTyped(evt);
            }
        });
        jPanel1.add(txtidcamarote);
        txtidcamarote.setBounds(250, 300, 140, 30);

        txtxantdadCamar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtxantdadCamarKeyTyped(evt);
            }
        });
        jPanel1.add(txtxantdadCamar);
        txtxantdadCamar.setBounds(250, 370, 140, 30);

        txtDescCam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescCamKeyTyped(evt);
            }
        });
        jPanel1.add(txtDescCam);
        txtDescCam.setBounds(600, 290, 140, 30);

        txtprecio1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprecio1KeyTyped(evt);
            }
        });
        jPanel1.add(txtprecio1);
        txtprecio1.setBounds(600, 340, 140, 30);

        jPanel2.setBackground(new java.awt.Color(38, 116, 162));

        txtbusqueda.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtbusqueda.setForeground(new java.awt.Color(51, 51, 51));
        txtbusqueda.setBorder(null);
        txtbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbusquedaActionPerformed(evt);
            }
        });
        txtbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbusquedaKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Candara", 2, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Buscar Camarote");

        btnbuscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lup32.png"))); // NOI18N
        btnbuscar1.setBorder(null);
        btnbuscar1.setBorderPainted(false);
        btnbuscar1.setContentAreaFilled(false);
        btnbuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnbuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(29, 29, 29))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 950, 72);
        jPanel1.add(txtprecio2);
        txtprecio2.setBounds(600, 340, 140, 20);

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Id Buque");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(510, 370, 70, 19);

        jLabel11.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Precio");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(510, 320, 45, 19);
        jPanel1.add(txtprecio3);
        txtprecio3.setBounds(600, 340, 140, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Camarote1.jpg"))); // NOI18N
        jLabel9.setText("jLabel2");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(0, 70, 950, 550);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnagregarActionPerformed

        if (txtxantdadCamar.getText().isEmpty() || txtDescCam.getText().isEmpty() || txtprecio1.getText().isEmpty() || txtidbuque.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tienes datos por llenar", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            limpiar();
        } else {
            try {
                ProcedimientoBuquesandCamarotes.insertCamarotes(txtxantdadCamar.getText(), txtDescCam.getText(), txtprecio1.getText(), txtidbuque.getText());
            } catch (SQLException ex) {

            }
        }
        cargatablebCamarotes();

    }//GEN-LAST:event_BtnagregarActionPerformed

    private void BtnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnupdateActionPerformed
        if (txtidcamarote.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ingrese el Id para actualizar", "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            int opc = JOptionPane.showConfirmDialog(this, "¿ESTAS SEGURO QUE DESEA ACTUALIZAR ESTE REGISTRO?", "Pregunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (opc == JOptionPane.YES_OPTION) {
                try {
                    ProcedimientoBuquesandCamarotes.UpdateCamarotes(Integer.parseInt(txtidcamarote.getText()),
                            txtxantdadCamar.getText(), txtDescCam.getText(), txtprecio1.getText(), txtidbuque.getText());
                } catch (SQLException e) {
                }
                cargatablebCamarotes();
                JOptionPane.showMessageDialog(null, "LOS DATOS HAN SIDO ACTUALIZADOS");
                limpiar();
            }
        }
    }//GEN-LAST:event_BtnupdateActionPerformed

    private void BtndeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtndeletActionPerformed
        if (txtidcamarote.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ingrese el Id para Eliminar", "Error", JOptionPane.ERROR_MESSAGE);
            limpiar();
        } else {
            int opc = JOptionPane.showConfirmDialog(this, "¿ESTAS SEGURO QUE DESEA ELIMINAR ESTE REGISTRO?", "Pregunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (opc == JOptionPane.YES_OPTION) {
                try {
                    ProcedimientoBuquesandCamarotes.deletCamarotes(Integer.parseInt(txtidcamarote.getText()));
                } catch (SQLException e) {
                }
                cargatablebCamarotes();
            }
        }
    }//GEN-LAST:event_BtndeletActionPerformed

    private void BtnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnlimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_BtnlimpiarActionPerformed

    private void txtbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbusquedaActionPerformed
/////////////////////////////////////////////////////////////////////////////////////Busqueda id oh descripcion ////


    private void txtbusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaKeyPressed


    }//GEN-LAST:event_txtbusquedaKeyPressed

    private void btnbuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar1ActionPerformed
        busqueda();
    }//GEN-LAST:event_btnbuscar1ActionPerformed

    private void txtidcamaroteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidcamaroteKeyPressed
       
    }//GEN-LAST:event_txtidcamaroteKeyPressed

    private void txtidcamaroteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidcamaroteKeyTyped
        char vali = evt.getKeyChar();
        if ((vali < '0' || vali > '9') && vali != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo ingrese numeros porfavor");
        }
    
            
    }//GEN-LAST:event_txtidcamaroteKeyTyped

    private void txtxantdadCamarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtxantdadCamarKeyTyped
        char vali = evt.getKeyChar();
        if ((vali < '0' || vali > '9') && vali != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo ingrese numeros porfavor");
        }
    }//GEN-LAST:event_txtxantdadCamarKeyTyped

    private void txtprecio1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprecio1KeyTyped
        char vali = evt.getKeyChar();
        if ((vali < '0' || vali > '9') && vali != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo ingrese numeros porfavor");
        }
    }//GEN-LAST:event_txtprecio1KeyTyped

    private void txtidbuqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidbuqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidbuqueActionPerformed

    private void txtidbuqueKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidbuqueKeyTyped
      char vali = evt.getKeyChar();
        if ((vali < '0' || vali > '9') && vali != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo ingrese numeros porfavor");
        }
    }//GEN-LAST:event_txtidbuqueKeyTyped

    private void txtDescCamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescCamKeyTyped
       char vali = evt.getKeyChar();
        if (Character.isDigit(vali) == false) {
        } else {
            JOptionPane.showMessageDialog(null, "Solo ingrese Letras porfavor");
            evt.consume();
        }
    }//GEN-LAST:event_txtDescCamKeyTyped

    ////////////Funcionesss /////////3
    //cargar datos de Camarates  //
    private void cargatablebCamarotes() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        res = Clases.ConexionBasedeDatos.Consulta("select * from Camarotes");
        try {
            while (res.next()) {
                Vector v = new Vector();
                v.add(res.getInt(1));
                v.add(res.getString(2));
                v.add(res.getString(3));
                v.add(res.getString(4));
                v.add(res.getString(5));

                model.addRow(v);
                jTable1.setModel(model);
            }
        } catch (SQLException e) {
        }
    }

    private void limpiar() {

        txtidcamarote.setText("");
        txtxantdadCamar.setText("");
        txtDescCam.setText("");
        txtprecio1.setText("");
        txtidbuque.setText("");
        txtidcamarote.requestFocus();

    }

    private void busqueda() {
        String consulta = "SELECT * FROM [dbo].[Camarotes] WHERE Id_Camarote LIKE '%" + txtbusqueda.getText() + "%' "
                + "OR Descripcion_Camarote LIKE '%" + txtbusqueda.getText() + "%'";

        Connection conect = ConexionBasedeDatos.getConexion();
        try {
            stModel = (Statement) conect.createStatement();
            rsModelo = stModel.executeQuery(consulta);
            while (rsModelo.next()) {
                txtidcamarote.setText(rsModelo.getString(1));
                txtxantdadCamar.setText(rsModelo.getString(2));
                txtDescCam.setText(rsModelo.getString(3));
                txtprecio1.setText(rsModelo.getString(4));
                txtidbuque.setText(rsModelo.getString(5));

                cargatablebCamarotes();

            }

        } catch (SQLException ex) {
            System.out.println("No existe : " + ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnagregar;
    private javax.swing.JButton Btndelet;
    private javax.swing.JButton Btnlimpiar;
    private javax.swing.JButton Btnupdate;
    private javax.swing.JButton btnbuscar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDescCam;
    private javax.swing.JTextField txtbusqueda;
    private javax.swing.JTextField txtidbuque;
    private javax.swing.JTextField txtidcamarote;
    private javax.swing.JTextField txtprecio1;
    private javax.swing.JTextField txtprecio2;
    private javax.swing.JTextField txtprecio3;
    private javax.swing.JTextField txtxantdadCamar;
    // End of variables declaration//GEN-END:variables
}
