/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Maykin Perdomo
 */
public class frmDestinos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Destinos
     */
    public frmDestinos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jPanel4 = new javax.swing.JPanel();
        txtbuscar2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BtnSalir = new javax.swing.JButton();
        Btneliminar = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        BtnAgrgar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtidturistico = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtidlugardestino = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txtbuscar3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(38, 116, 162));
        jPanel4.setLayout(null);

        txtbuscar2.setBackground(new java.awt.Color(17, 51, 71));
        txtbuscar2.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtbuscar2.setForeground(new java.awt.Color(255, 255, 255));
        txtbuscar2.setBorder(null);
        jPanel4.add(txtbuscar2);
        txtbuscar2.setBounds(690, 607, 265, 19);

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Buscar Destino");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(579, 607, 107, 19);

        jLabel17.setFont(new java.awt.Font("Gill Sans MT", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Destinos");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(39, 588, 148, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(193, 189, 0, 0);

        jPanel1.setBackground(new java.awt.Color(26, 78, 108));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnSalir.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        BtnSalir.setForeground(new java.awt.Color(255, 255, 255));
        BtnSalir.setText("Salir");
        jPanel1.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 120, 60));

        Btneliminar.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        Btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        Btneliminar.setText("Eliminar");
        jPanel1.add(Btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 120, 60));

        BtnActualizar.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        BtnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        BtnActualizar.setText("Actualizar");
        jPanel1.add(BtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 120, 60));

        BtnAgrgar.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        BtnAgrgar.setForeground(new java.awt.Color(255, 255, 255));
        BtnAgrgar.setText("Agregar");
        jPanel1.add(BtnAgrgar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 120, 60));

        jLabel3.setBackground(new java.awt.Color(21, 38, 76));
        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(21, 38, 76));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("EMPACA TU TRAJE DE BUCEO");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("cerca en una aventura de buceo o buceo con esnórquel.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        jTable1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 830, 120));

        txtidturistico.setBackground(new java.awt.Color(17, 51, 71));
        txtidturistico.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtidturistico.setForeground(new java.awt.Color(255, 255, 255));
        txtidturistico.setBorder(null);
        jPanel1.add(txtidturistico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 170, -1));

        txtDescripcion.setBackground(new java.awt.Color(17, 51, 71));
        txtDescripcion.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        txtDescripcion.setBorder(null);
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 170, -1));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID Lugar");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Descripcion");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, -1));

        jComboBox3.setBackground(new java.awt.Color(17, 51, 71));
        jComboBox3.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setBorder(null);
        jPanel1.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 210, -1));

        jLabel14.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Buque");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, -1));

        txtidlugardestino.setBackground(new java.awt.Color(17, 51, 71));
        txtidlugardestino.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtidlugardestino.setForeground(new java.awt.Color(255, 255, 255));
        txtidlugardestino.setBorder(null);
        jPanel1.add(txtidlugardestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 170, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 60, 880, 490);

        jPanel5.setBackground(new java.awt.Color(38, 116, 162));

        txtbuscar3.setBackground(new java.awt.Color(17, 51, 71));
        txtbuscar3.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtbuscar3.setForeground(new java.awt.Color(255, 255, 255));
        txtbuscar3.setBorder(null);

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Buscar Destino");

        jLabel18.setFont(new java.awt.Font("Gill Sans MT", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Destinos");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtbuscar3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 880, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnAgrgar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton Btneliminar;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtbuscar2;
    private javax.swing.JTextField txtbuscar3;
    private javax.swing.JTextField txtidlugardestino;
    private javax.swing.JTextField txtidturistico;
    // End of variables declaration//GEN-END:variables
}
