/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.ConexionBasedeDatos;
import Clases.ProcedimientoBuquesandCamarotes;
import static GUI.frmBuque.res;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maykin Perdomo
 */
public class frminsertabuqe extends javax.swing.JFrame {

    Connection cn = ConexionBasedeDatos.obtenerConexion();
    DefaultTableModel modelo = new DefaultTableModel();
    PreparedStatement ps = null;
    Statement stModel = null;
    ResultSet rsModelo = null;
    String id;

    public frminsertabuqe() {
        initComponents();
        cargatipbuque();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtbuscar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        BtnEliminar = new javax.swing.JButton();
        BtnActualizar = new javax.swing.JButton();
        BtnAgregar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtid = new javax.swing.JTextField();
        txtdesc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtmodelo = new javax.swing.JTextField();
        txtmarca = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Btnlimpiar1 = new javax.swing.JButton();
        BtnEliminar1 = new javax.swing.JButton();
        Btnlimpiar3 = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(38, 116, 162));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtbuscar.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtbuscar.setForeground(new java.awt.Color(51, 51, 51));
        txtbuscar.setBorder(null);
        jPanel2.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 33, 265, -1));

        jLabel6.setFont(new java.awt.Font("Candara", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Buscar Tipo Buque");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 37, -1, -1));

        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lup32.png"))); // NOI18N
        btnbuscar.setBorder(null);
        btnbuscar.setBorderPainted(false);
        btnbuscar.setContentAreaFilled(false);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 33, 25, 22));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        BtnEliminar.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        BtnEliminar.setForeground(new java.awt.Color(17, 51, 71));
        BtnEliminar.setText("Eliminar");
        BtnEliminar.setBorder(null);
        BtnEliminar.setBorderPainted(false);
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEliminar);
        BtnEliminar.setBounds(440, 390, 140, 30);

        BtnActualizar.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        BtnActualizar.setForeground(new java.awt.Color(17, 51, 71));
        BtnActualizar.setText("Actualizar");
        BtnActualizar.setBorder(null);
        BtnActualizar.setBorderPainted(false);
        BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnActualizar);
        BtnActualizar.setBounds(290, 390, 140, 30);

        BtnAgregar.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        BtnAgregar.setForeground(new java.awt.Color(17, 51, 71));
        BtnAgregar.setText("Agregar");
        BtnAgregar.setBorder(null);
        BtnAgregar.setBorderPainted(false);
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnAgregar);
        BtnAgregar.setBounds(140, 390, 140, 30);

        jTable1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID_Tipo_Buque", "Descripcion", "Marca", "Modelo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 870, 100);

        txtid.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtid.setForeground(new java.awt.Color(51, 51, 51));
        txtid.setBorder(null);
        txtid.setEnabled(false);
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidKeyTyped(evt);
            }
        });
        jPanel1.add(txtid);
        txtid.setBounds(240, 240, 160, 30);

        txtdesc.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtdesc.setForeground(new java.awt.Color(51, 51, 51));
        txtdesc.setBorder(null);
        txtdesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescActionPerformed(evt);
            }
        });
        txtdesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdescKeyTyped(evt);
            }
        });
        jPanel1.add(txtdesc);
        txtdesc.setBounds(240, 300, 160, 30);

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Tipo buque");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(170, 220, 110, 19);

        jLabel8.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Descripcion ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(170, 280, 90, 19);

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Marca");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(460, 220, 54, 19);

        jLabel12.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Modelo");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(460, 280, 60, 19);

        txtmodelo.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtmodelo.setForeground(new java.awt.Color(51, 51, 51));
        txtmodelo.setBorder(null);
        txtmodelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmodeloKeyTyped(evt);
            }
        });
        jPanel1.add(txtmodelo);
        txtmodelo.setBounds(510, 300, 160, 30);

        txtmarca.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtmarca.setForeground(new java.awt.Color(51, 51, 51));
        txtmarca.setBorder(null);
        txtmarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmarcaKeyTyped(evt);
            }
        });
        jPanel1.add(txtmarca);
        txtmarca.setBounds(510, 240, 160, 30);

        jLabel15.setFont(new java.awt.Font("Gill Sans MT", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Tipos Buques");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(340, 130, 240, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icono100x100_1.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 470, 100, 110);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tipobuqeu.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 20, 870, 870);

        Btnlimpiar1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        Btnlimpiar1.setForeground(new java.awt.Color(17, 51, 71));
        Btnlimpiar1.setText("Limpiar");
        Btnlimpiar1.setBorder(null);
        Btnlimpiar1.setBorderPainted(false);
        Btnlimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btnlimpiar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Btnlimpiar1);
        Btnlimpiar1.setBounds(600, 390, 150, 30);

        BtnEliminar1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        BtnEliminar1.setForeground(new java.awt.Color(17, 51, 71));
        BtnEliminar1.setText("Eliminar");
        BtnEliminar1.setBorder(null);
        BtnEliminar1.setBorderPainted(false);
        BtnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminar1ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEliminar1);
        BtnEliminar1.setBounds(560, 420, 140, 30);

        Btnlimpiar3.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        Btnlimpiar3.setForeground(new java.awt.Color(17, 51, 71));
        Btnlimpiar3.setText("Limpiar");
        Btnlimpiar3.setBorder(null);
        Btnlimpiar3.setBorderPainted(false);
        Btnlimpiar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btnlimpiar3ActionPerformed(evt);
            }
        });
        jPanel1.add(Btnlimpiar3);
        Btnlimpiar3.setBounds(600, 390, 150, 30);

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, 870, 566));

        BtnSalir.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        BtnSalir.setForeground(new java.awt.Color(17, 51, 71));
        BtnSalir.setText("Salir");
        BtnSalir.setBorder(null);
        BtnSalir.setBorderPainted(false);
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(774, 25, 72, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        if (txtid.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ingrese el Id para Eliminar", "Error", JOptionPane.ERROR_MESSAGE);
            limpiar();
        } else {
            int opc = JOptionPane.showConfirmDialog(this, "¿ESTAS SEGURO QUE DESEA ELIMINAR ESTE REGISTRO?", "Pregunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (opc == JOptionPane.YES_OPTION) {
                try {
                    ProcedimientoBuquesandCamarotes.DelettipoBuque(Integer.parseInt(txtid.getText()));
                } catch (SQLException e) {
                }
                cargatipbuque();
            }
        }
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarActionPerformed
        if (txtid.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "ingrese el Id para actualizar", "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            int opc = JOptionPane.showConfirmDialog(this, "¿ESTAS SEGURO QUE DESEA ACTUALIZAR ESTE REGISTRO?", "Pregunta", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (opc == JOptionPane.YES_OPTION) {
                try {
                    ProcedimientoBuquesandCamarotes.Updatetipobuque(Integer.parseInt(txtid.getText()), txtdesc.getText(), txtmarca.getText(), txtmodelo.getText());
                } catch (SQLException e) {
                }
                cargatipbuque();
                JOptionPane.showMessageDialog(null, "LOS DATOS HAN SIDO ACTUALIZADOS");
                limpiar();
            }
        }
    }//GEN-LAST:event_BtnActualizarActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        if (txtdesc.getText().isEmpty() || txtmodelo.getText().isEmpty() || txtmarca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tienes datos por llenar", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            limpiar();
        } else {
            try {
                ProcedimientoBuquesandCamarotes.insertTipoBuque(txtdesc.getText(), txtmarca.getText(), txtmodelo.getText());
            } catch (SQLException ex) {

            }
        }
        cargatipbuque();
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void txtidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyTyped
        char vali = evt.getKeyChar();
        if ((vali < '0' || vali > '9') && vali != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo ingrese numeros porfavor");
        }

    }//GEN-LAST:event_txtidKeyTyped

    private void txtdescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescActionPerformed

    private void txtdescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescKeyTyped
        char vali = evt.getKeyChar();
        if (Character.isDigit(vali) == false) {
        } else {
            JOptionPane.showMessageDialog(null, "Solo ingrese Letras porfavor");
            evt.consume();
        }
    }//GEN-LAST:event_txtdescKeyTyped

    private void txtmarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmarcaKeyTyped
        char vali = evt.getKeyChar();
        if (Character.isDigit(vali) == false) {
        } else {
            JOptionPane.showMessageDialog(null, "Solo ingrese Letras porfavor");
            evt.consume();
        }
    }//GEN-LAST:event_txtmarcaKeyTyped

    private void Btnlimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btnlimpiar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btnlimpiar1ActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        BusquedaTipoBuques(txtbuscar.getText());
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void BtnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEliminar1ActionPerformed

    private void Btnlimpiar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btnlimpiar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btnlimpiar3ActionPerformed

    private void txtmodeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmodeloKeyTyped
        char vali = evt.getKeyChar();
        if (Character.isDigit(vali) == false) {
        } else {
            JOptionPane.showMessageDialog(null, "Solo ingrese Letras porfavor");
            evt.consume();
        }
    }//GEN-LAST:event_txtmodeloKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        id = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        BusquedaTipoBuques(id);
    }//GEN-LAST:event_jTable1MouseClicked

    private void cargatipbuque() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        res = Clases.ConexionBasedeDatos.Consulta("select * from Tipo_Buques");
        try {
            while (res.next()) {
                Vector v = new Vector();
                v.add(res.getInt(1));
                v.add(res.getString(2));
                v.add(res.getString(3));
                v.add(res.getString(4));

                model.addRow(v);
                jTable1.setModel(model);
            }
        } catch (SQLException e) {
        }
    }

    private void limpiar() {

        txtid.setText("");
        txtdesc.setText("");
        txtmarca.setText("");
        txtmodelo.setText("");

    }

    public void BusquedaTipoBuques(String id) {

        String consulta = "SELECT * FROM [dbo].[Tipo_Buques]  WHERE [Id-TipoBuque] LIKE '%" + id + "%' "
                + "OR [DescripcionBuque] LIKE '%" + id + "%'";

        Connection conect = ConexionBasedeDatos.obtenerConexion();
        try {
            stModel = (Statement) conect.createStatement();
            rsModelo = stModel.executeQuery(consulta);
            while (rsModelo.next()) {
                txtid.setText(rsModelo.getString(1));
                txtdesc.setText(rsModelo.getString(2));
                txtmarca.setText(rsModelo.getString(3));
                txtmodelo.setText(rsModelo.getString(4));

                cargatipbuque();

            }

        } catch (SQLException ex) {

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizar;
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnEliminar1;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton Btnlimpiar1;
    private javax.swing.JButton Btnlimpiar3;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtdesc;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JTextField txtmodelo;
    // End of variables declaration//GEN-END:variables
}
